### ISSUE TITLE
multiple heroes had the following tag: <default FloatingActionButton tag>

### ISSUE THREAD

**Issue by zubairzahoor** [UttamPanchasara/Flutter-Floating-Menu#1]
When you try to open a route from the route that has this menu, the screen goes blank as there are multiple floating buttons that supposedly use the same hero tag. They should ideally be using different tags. Am I missing something here? 
The following assertion was thrown during a scheduler callback:
I/flutter ( 5902): There are multiple heroes that share the same tag within a subtree.
I/flutter ( 5902): Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
I/flutter ( 5902): have a unique non-null tag.
I/flutter ( 5902): In this case, multiple heroes had the following tag: <default FloatingActionButton tag>

**Comment by UttamPanchasara** [comment]
Hi,

I applied the fix of your problem, Please get the latest package v-0.0.2.

NOTE: Please tries to provide a unique id for each menu item.

Let me know if you face any other issue.
Thanks.

**Comment by zubairzahoor** [comment]
Thank you for a prompt response. I fixed it by putting 'heroTag:null' for floating menu items.

**Comment by UttamPanchasara** [comment]
Good to know :)
But as I have put the value for heroTag in package, I think you don;t have to put value for heroTag so try by removing that and verify it once, and let me know if it is working with you or no.

**Comment by zubairzahoor** [comment]
Yes, works flawlessly, but I am sticking to v1 as I cloned your repository and made some changes according to my needs like a label beside the icon among other things.
Good Work!
